version: '3.8'

services:
  controlpanel.server:
    build:
      context: .
      dockerfile: ControlPanel.Server/Dockerfile
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
    networks:
      - controlpanel-network

  controlpanel.ui:
    build:
      context: .
      dockerfile: ControlPanel.Ui/Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - controlpanel.server
    networks:
      - controlpanel-network

networks:
  controlpanel-network:
    driver: bridge